/**
 * Pure reducer for the chat turn state.
 *
 * IDs are pre-generated by the caller before each dispatch so the reducer
 * stays side-effect free and is fully unit-testable without mocking React.
 */

// ── Item types ────────────────────────────────────────────────────────────────

export interface TextItem {
  kind: 'text'
  id: string
  content: string
}

export interface ToolItem {
  kind: 'tool'
  id: string
  /** Matches the `id` field of the pi `tool_use` event — used to correlate results. */
  toolUseId: string
  name: string
  input: unknown
  result?: unknown
  pending: boolean
}

export type AssistantItem = TextItem | ToolItem

// ── Turn types ────────────────────────────────────────────────────────────────

export interface UserTurn {
  id: string
  kind: 'user'
  text: string
}

export interface AssistantTurn {
  id: string
  kind: 'assistant'
  items: AssistantItem[]
  /** True once turn_end or execution_complete fired — stops the Thinking… spinner even for empty responses. */
  completed: boolean
}

export type Turn = UserTurn | AssistantTurn

// ── Actions ───────────────────────────────────────────────────────────────────

export type TurnsAction =
  | { type: 'RESET' }
  | { type: 'USER_TURN'; id: string; text: string }
  | { type: 'AGENT_START'; id: string }
  | { type: 'TURN_COMPLETE'; id: string }
  | {
      type: 'TEXT_DELTA'
      /** ID of the assistant turn currently being built (null = no turn started yet). */
      currentAssistantId: string | null
      delta: string
      /** Pre-generated ID for a new assistant turn — used only when currentAssistantId is null. */
      newTurnId: string
      /** Pre-generated ID for a new text item — used when a new item must be created. */
      newItemId: string
    }
  | {
      type: 'TOOL_USE'
      /** ID of the assistant turn currently being built (null = no turn started yet). */
      currentAssistantId: string | null
      item: ToolItem
      /** Pre-generated ID for a new assistant turn — used only when currentAssistantId is null. */
      newTurnId: string
    }
  | { type: 'TOOL_RESULT'; toolUseId: string; content: unknown }

// ── Reducer ───────────────────────────────────────────────────────────────────

export function turnsReducer(state: Turn[], action: TurnsAction): Turn[] {
  switch (action.type) {
    case 'RESET':
      return []

    case 'USER_TURN':
      return [...state, { id: action.id, kind: 'user', text: action.text }]

    case 'AGENT_START':
      return [...state, { id: action.id, kind: 'assistant', items: [], completed: false }]

    case 'TURN_COMPLETE':
      return state.map(turn =>
        turn.id === action.id && turn.kind === 'assistant'
          ? { ...turn, completed: true }
          : turn
      )

    case 'TEXT_DELTA': {
      const { currentAssistantId, delta, newTurnId, newItemId } = action

      if (!currentAssistantId) {
        // No active assistant turn — create one with the initial text item.
        return [
          ...state,
          {
            id: newTurnId,
            kind: 'assistant',
            completed: false,
            items: [{ kind: 'text', id: newItemId, content: delta }],
          },
        ]
      }

      return state.map(turn => {
        if (turn.id !== currentAssistantId || turn.kind !== 'assistant') return turn
        const items = turn.items
        const last = items[items.length - 1]

        if (last && last.kind === 'text') {
          // Append to the trailing text item — avoids O(n) fragmentation.
          return {
            ...turn,
            items: [...items.slice(0, -1), { ...last, content: last.content + delta }],
          }
        }

        // Last item was a tool card — start a new text item after it.
        return {
          ...turn,
          items: [...items, { kind: 'text', id: newItemId, content: delta }],
        }
      })
    }

    case 'TOOL_USE': {
      const { currentAssistantId, item, newTurnId } = action

      if (!currentAssistantId) {
        return [...state, { id: newTurnId, kind: 'assistant', completed: false, items: [item] }]
      }

      return state.map(turn => {
        if (turn.id !== currentAssistantId || turn.kind !== 'assistant') return turn
        return { ...turn, items: [...turn.items, item] }
      })
    }

    case 'TOOL_RESULT': {
      const { toolUseId, content } = action
      return state.map(turn => {
        if (turn.kind !== 'assistant') return turn
        const items = turn.items.map(item => {
          if (item.kind === 'tool' && item.toolUseId === toolUseId) {
            return { ...item, result: content, pending: false }
          }
          return item
        })
        return { ...turn, items }
      })
    }

    default:
      return state
  }
}
